package com.netflix.identity_service.service;

import com.netflix.identity_service.dto.AuthResponse;
import com.netflix.identity_service.dto.LoginRequest;
import com.netflix.identity_service.dto.RegisterRequest;
import com.netflix.identity_service.entity.Role;
import com.netflix.identity_service.entity.RoleName;
import com.netflix.identity_service.entity.User;
import com.netflix.identity_service.repository.RoleRepository;
import com.netflix.identity_service.repository.UserRepository;
import com.netflix.identity_service.security.JwtTokenProvider;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.Collections;

@Service
@RequiredArgsConstructor
@Slf4j
public class AuthService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtTokenProvider jwtTokenProvider;
    private final RoleRepository roleRepository;

    // 1. Registration Logic
    @Transactional // Ensures atomicity: if role assignment fails, the user isn't created
    public void register(RegisterRequest request) {
        if (userRepository.existsByUsername(request.getUsername())) {
            throw new RuntimeException("Username already exists");
        }

        User user = new User();
        user.setUsername(request.getUsername());
        // Production Rule: Always encrypt the password before saving
        user.setPassword(passwordEncoder.encode(request.getPassword()));

        // Fetch ROLE_USER from DB and assign it
        Role userRole = roleRepository.findByName(RoleName.ROLE_USER)
                .orElseThrow(() -> new RuntimeException("Error: Role not found."));

        user.setRoles(Collections.singleton(userRole));

        userRepository.save(user);
        log.info("User registered: {}", request.getUsername());
    }

    // 2. Authentication Logic
    public AuthResponse authenticate(LoginRequest request) {
        User user = userRepository.findByUsername(request.getUsername())
                .orElseThrow(() -> new RuntimeException("Invalid credentials"));

        if (!passwordEncoder.matches(request.getPassword(), user.getPassword())) {
            throw new RuntimeException("Invalid credentials");
        }

        // Return the JWT generated by our engine
        String token = jwtTokenProvider.generateToken(user.getUsername());

        // Returning the DTO
        return new AuthResponse(token, jwtTokenProvider.getExpirationTime());
    }
}